(define (problem dog1)
  (:domain petshop)
  (:objects home store jack dog)
  (:init (at jack home) (at dog store)
	 (pet dog)
	 (mobile jack)
	 (person jack))
  (:goal (and (at dog home) (at jack home)))
  )
