/* Generated By:JavaCC: Do not edit this line. LexerTreeConstants.java Version 4.2 */
namespace PDDLParser.Parser.Lexer
{

public class LexerTreeConstants
{
  public const int JJTROOT = 0;
  public const int JJTDOMAIN = 1;
  public const int JJTREQUIRE_DEF = 2;
  public const int JJTREQUIRE_KEY = 3;
  public const int JJTTYPE_DEF = 4;
  public const int JJTTYPED_LIST = 5;
  public const int JJTTYPE = 6;
  public const int JJTPRIMITIVE_TYPE = 7;
  public const int JJTCONSTANT_DEF = 8;
  public const int JJTCONSTANT = 9;
  public const int JJTPREDICATE_DEF = 10;
  public const int JJTATTRIBUTE = 11;
  public const int JJTATOMIC_FORMULA_SKELETON = 12;
  public const int JJTATOMIC_FORMULA_SKELETON_DECLARATION = 13;
  public const int JJTPREDICATE = 14;
  public const int JJTVARIABLE = 15;
  public const int JJTFUNCTION_DEF = 16;
  public const int JJTATOMIC_FUNCTION_SKELETON = 17;
  public const int JJTATOMIC_FUNCTION_SKELETON_DECLARATION = 18;
  public const int JJTFUNCTOR = 19;
  public const int JJTFUNCTION_TYPED_LIST = 20;
  public const int JJTTYPED_FUNCTION = 21;
  public const int JJTFUNCTION_TYPE = 22;
  public const int JJTCON_GD = 23;
  public const int JJTAND_CON_GD = 24;
  public const int JJTOR_CON_GD = 25;
  public const int JJTXOR_UNIQUE_CON_GD = 26;
  public const int JJTNOT_CON_GD = 27;
  public const int JJTIMPLY_CON_GD = 28;
  public const int JJTIF_THEN_ELSE_CON_GD = 29;
  public const int JJTEXISTS_CON_GD = 30;
  public const int JJTEXISTS_UNIQUE_CON_GD = 31;
  public const int JJTFORALL_CON_GD = 32;
  public const int JJTAT_END_CON_GD = 33;
  public const int JJTT_ALWAYS_CON_GD = 34;
  public const int JJTT_EVENTUALLY_CON_GD = 35;
  public const int JJTT_UNTIL_CON_GD = 36;
  public const int JJTALWAYS_CON_GD = 37;
  public const int JJTUNTIL_CON_GD = 38;
  public const int JJTWEAK_UNTIL_CON_GD = 39;
  public const int JJTNEXT_CON_GD = 40;
  public const int JJTSOMETIME_CON_GD = 41;
  public const int JJTWITHIN_CON_GD = 42;
  public const int JJTAT_MOST_ONCE_CON_GD = 43;
  public const int JJTSOMETIME_AFTER_CON_GD = 44;
  public const int JJTSOMETIME_BEFORE_CON_GD = 45;
  public const int JJTALWAYS_WITHIN_CON_GD = 46;
  public const int JJTHOLD_DURING_CON_GD = 47;
  public const int JJTHOLD_AFTER_CON_GD = 48;
  public const int JJTTIME_INTERVAL = 49;
  public const int JJTLOWER_TIME_BOUND = 50;
  public const int JJTLOWER_BOUND_TYPE = 51;
  public const int JJTLOWER_BOUND_TIME = 52;
  public const int JJTNEGATIVE_INFINITY = 53;
  public const int JJTUPPER_TIME_BOUND = 54;
  public const int JJTUPPER_BOUND_TYPE = 55;
  public const int JJTUPPER_BOUND_TIME = 56;
  public const int JJTPOSITIVE_INFINITY = 57;
  public const int JJTSUB_CON_GD = 58;
  public const int JJTAND_SUB_CON_GD = 59;
  public const int JJTOR_SUB_CON_GD = 60;
  public const int JJTXOR_UNIQUE_SUB_CON_GD = 61;
  public const int JJTNOT_SUB_CON_GD = 62;
  public const int JJTIMPLY_SUB_CON_GD = 63;
  public const int JJTIF_THEN_ELSE_SUB_CON_GD = 64;
  public const int JJTEXISTS_SUB_CON_GD = 65;
  public const int JJTEXISTS_UNIQUE_SUB_CON_GD = 66;
  public const int JJTFORALL_SUB_CON_GD = 67;
  public const int JJTGD = 68;
  public const int JJTGOAL_MODALITY = 69;
  public const int JJTASSIGN_LOCAL_VAR = 70;
  public const int JJTFUNCTION_OR_VARIABLE = 71;
  public const int JJTLOCAL_VALUE = 72;
  public const int JJTAND_GD = 73;
  public const int JJTOR_GD = 74;
  public const int JJTXOR_UNIQUE_GD = 75;
  public const int JJTNOT_GD = 76;
  public const int JJTIMPLY_GD = 77;
  public const int JJTIF_THEN_ELSE_GD = 78;
  public const int JJTEXISTS_GD = 79;
  public const int JJTEXISTS_UNIQUE_GD = 80;
  public const int JJTFORALL_GD = 81;
  public const int JJTATOMIC_FORMULA = 82;
  public const int JJTTERM = 83;
  public const int JJTFUNCTION_TERM_OR_CONSTANT = 84;
  public const int JJTLITERAL = 85;
  public const int JJTNOT_ATOMIC_FORMULA = 86;
  public const int JJTF_COMP = 87;
  public const int JJTBINARY_COMP = 88;
  public const int JJTGREATER_COMP = 89;
  public const int JJTGREATER_EQUAL_COMP = 90;
  public const int JJTLESS_EQUAL_COMP = 91;
  public const int JJTLESS_COMP = 92;
  public const int JJTEQUAL_COMP = 93;
  public const int JJTF_EXP = 94;
  public const int JJTNUMBER = 95;
  public const int JJTOP = 96;
  public const int JJTADD_OP = 97;
  public const int JJTSUBSTRACT_OP = 98;
  public const int JJTMULTIPLY_OP = 99;
  public const int JJTDIVIDE_OP = 100;
  public const int JJTMOD_OP = 101;
  public const int JJTMAX_OP = 102;
  public const int JJTMIN_OP = 103;
  public const int JJTEXPT_OP = 104;
  public const int JJTSQRT_OP = 105;
  public const int JJTABS_OP = 106;
  public const int JJTLOG_OP = 107;
  public const int JJTEXP_OP = 108;
  public const int JJTROUND_OP = 109;
  public const int JJTINT_OP = 110;
  public const int JJTFLOOR_OP = 111;
  public const int JJTCEIL_OP = 112;
  public const int JJTF_HEAD = 113;
  public const int JJTFUNCTION_HEAD = 114;
  public const int JJTFUNCTION_HEAD_OR_FUNCTOR = 115;
  public const int JJTDECLARE_DEFINED_SYMBOLS = 116;
  public const int JJTSTRUCTURE_DEF = 117;
  public const int JJTDEFINED_FORMULA_DECLARATION = 118;
  public const int JJTDEFINED_FORMULA = 119;
  public const int JJTACTION_DEF = 120;
  public const int JJTACTION_NAME = 121;
  public const int JJTACTION_DEF_BODY = 122;
  public const int JJTPRE_GD = 123;
  public const int JJTEMPTY_OR = 124;
  public const int JJTAND_PRE_GD = 125;
  public const int JJTFORALL_PRE_GD = 126;
  public const int JJTPREF_GD = 127;
  public const int JJTNAMED_PREF_GD = 128;
  public const int JJTPREF_NAME = 129;
  public const int JJTEFFECT = 130;
  public const int JJTAND_C_EFFECT = 131;
  public const int JJTC_EFFECT = 132;
  public const int JJTFORALL_EFFECT = 133;
  public const int JJTWHEN_CON_EFFECT = 134;
  public const int JJTCOND_EFFECT = 135;
  public const int JJTAND_P_EFFECT = 136;
  public const int JJTP_EFFECT = 137;
  public const int JJTF_EXP_OR_TERM = 138;
  public const int JJTF_EXP_OR_TERM_OR_UNDEFINED = 139;
  public const int JJTASSIGN_OP = 140;
  public const int JJTASSIGN = 141;
  public const int JJTSCALE_UP = 142;
  public const int JJTSCALE_DOWN = 143;
  public const int JJTINCREASE = 144;
  public const int JJTDECREASE = 145;
  public const int JJTDURATION_ACTION_DEF = 146;
  public const int JJTDA_DEF_BODY = 147;
  public const int JJTDURATION_CONSTRAINT = 148;
  public const int JJTAND_SIMPLE_DURATION_CONSTRAINT = 149;
  public const int JJTSIMPLE_DURATION_CONSTRAINT = 150;
  public const int JJTAT_SIMPLE_DURATION_CONSTRAINT = 151;
  public const int JJTAT_START_SIMPLE_DURATION_CONSTRAINT = 152;
  public const int JJTAT_END_SIMPLE_DURATION_CONSTRAINT = 153;
  public const int JJTD_OP = 154;
  public const int JJTEQUAL_D_OP = 155;
  public const int JJTGEQUAL_D_OP = 156;
  public const int JJTLEQUAL_D_OP = 157;
  public const int JJTVAR_DURATION = 158;
  public const int JJTD_VALUE = 159;
  public const int JJTDA_GD = 160;
  public const int JJTFORALL_DA_GD = 161;
  public const int JJTAND_DA_GD = 162;
  public const int JJTPREF_TIMED_GD = 163;
  public const int JJTNAMED_PREF_TIMED_GD = 164;
  public const int JJTTIMED_GD = 165;
  public const int JJTOVER_TIMED_GD = 166;
  public const int JJTOVER_ALL_TIMED_GD = 167;
  public const int JJTAT_TIMED_GD = 168;
  public const int JJTAT_START_TIMED_GD = 169;
  public const int JJTAT_END_TIMED_GD = 170;
  public const int JJTINTERVAL = 171;
  public const int JJTDA_EFFECT = 172;
  public const int JJTWHEN_DA_EFFECT = 173;
  public const int JJTFORALL_DA_EFFECT = 174;
  public const int JJTAND_DA_EFFECT = 175;
  public const int JJTTIMED_EFFECT = 176;
  public const int JJTAT_F_ASSIGN_DA_EFFECT = 177;
  public const int JJTAT_START_F_ASSIGN_DA_EFFECT = 178;
  public const int JJTAT_END_F_ASSIGN_DA_EFFECT = 179;
  public const int JJTAT_DA_EFFECT = 180;
  public const int JJTAT_START_DA_EFFECT = 181;
  public const int JJTAT_END_DA_EFFECT = 182;
  public const int JJTASSIGN_OP_T = 183;
  public const int JJTINCREASE_ASSIGN_OP_T = 184;
  public const int JJTDECREASE_ASSIGN_OP_T = 185;
  public const int JJTF_EXP_T = 186;
  public const int JJTCONTINOUS_VARIABLE = 187;
  public const int JJTF_EXP_DA = 188;
  public const int JJTDA_OP = 189;
  public const int JJTDA_ADD_OP = 190;
  public const int JJTDA_SUBSTRACT_OP = 191;
  public const int JJTDA_MULTIPLY_OP = 192;
  public const int JJTDA_DIVIDE_OP = 193;
  public const int JJTDERIVED_DEF = 194;
  public const int JJTDERIVED_DEF_DECLARATION = 195;
  public const int JJTDEFINED_PREDICATE = 196;
  public const int JJTDEFINED_PREDICATE_DECLARATION = 197;
  public const int JJTDEFINED_FUNCTION = 198;
  public const int JJTDEFINED_FUNCTION_DECLARATION = 199;
  public const int JJTLOCAL_VARS = 200;
  public const int JJTPROBLEM = 201;
  public const int JJTPROBLEM_NAME = 202;
  public const int JJTDOMAIN_NAME = 203;
  public const int JJTOBJECT_DECLARATION = 204;
  public const int JJTINIT = 205;
  public const int JJTINIT_EL = 206;
  public const int JJTEQUAL_INIT_EL = 207;
  public const int JJTNUMBER_OR_CONSTANT = 208;
  public const int JJTTIMED_LITERAL = 209;
  public const int JJTGOAL = 210;
  public const int JJTCONSTRAINTS = 211;
  public const int JJTPREF_CON_GD = 212;
  public const int JJTAND_PREF_CON_GD = 213;
  public const int JJTNAMED_PREF_CON_GD = 214;
  public const int JJTFORALL_PREF_CON_GD = 215;
  public const int JJTMETRIC_SPEC = 216;
  public const int JJTMAXIMIZE = 217;
  public const int JJTMINIMIZE = 218;
  public const int JJTMETRIC_F_EXP = 219;
  public const int JJTVIOLATED_PREF_EXP = 220;
  public const int JJTCONSTANT_F_HEAD = 221;
  public const int JJTCONSTANT_FUNCTION_HEAD = 222;
  public const int JJTCONSTANT_FUNCTION_HEAD_OR_FUNCTOR = 223;
  public const int JJTTOTAL_TIME = 224;
  public const int JJTMULTI_OP_METRIC_F_EXP = 225;
  public const int JJTMULTIPLY_NARITY_OP_METRIC_F_EXP = 226;
  public const int JJTDIVIDE_NARITY_OP_METRIC_F_EXP = 227;
  public const int JJTADD_NARITY_OP_METRIC_F_EXP = 228;
  public const int JJTSUBSTRACT_NARITY_OP_METRIC_F_EXP = 229;


  public static string[] jjtNodeName = {
    "ROOT",
    "DOMAIN",
    "REQUIRE_DEF",
    "REQUIRE_KEY",
    "TYPE_DEF",
    "TYPED_LIST",
    "TYPE",
    "PRIMITIVE_TYPE",
    "CONSTANT_DEF",
    "CONSTANT",
    "PREDICATE_DEF",
    "ATTRIBUTE",
    "ATOMIC_FORMULA_SKELETON",
    "ATOMIC_FORMULA_SKELETON_DECLARATION",
    "PREDICATE",
    "VARIABLE",
    "FUNCTION_DEF",
    "ATOMIC_FUNCTION_SKELETON",
    "ATOMIC_FUNCTION_SKELETON_DECLARATION",
    "FUNCTOR",
    "FUNCTION_TYPED_LIST",
    "TYPED_FUNCTION",
    "FUNCTION_TYPE",
    "CON_GD",
    "AND_CON_GD",
    "OR_CON_GD",
    "XOR_UNIQUE_CON_GD",
    "NOT_CON_GD",
    "IMPLY_CON_GD",
    "IF_THEN_ELSE_CON_GD",
    "EXISTS_CON_GD",
    "EXISTS_UNIQUE_CON_GD",
    "FORALL_CON_GD",
    "AT_END_CON_GD",
    "T_ALWAYS_CON_GD",
    "T_EVENTUALLY_CON_GD",
    "T_UNTIL_CON_GD",
    "ALWAYS_CON_GD",
    "UNTIL_CON_GD",
    "WEAK_UNTIL_CON_GD",
    "NEXT_CON_GD",
    "SOMETIME_CON_GD",
    "WITHIN_CON_GD",
    "AT_MOST_ONCE_CON_GD",
    "SOMETIME_AFTER_CON_GD",
    "SOMETIME_BEFORE_CON_GD",
    "ALWAYS_WITHIN_CON_GD",
    "HOLD_DURING_CON_GD",
    "HOLD_AFTER_CON_GD",
    "TIME_INTERVAL",
    "LOWER_TIME_BOUND",
    "LOWER_BOUND_TYPE",
    "LOWER_BOUND_TIME",
    "NEGATIVE_INFINITY",
    "UPPER_TIME_BOUND",
    "UPPER_BOUND_TYPE",
    "UPPER_BOUND_TIME",
    "POSITIVE_INFINITY",
    "SUB_CON_GD",
    "AND_SUB_CON_GD",
    "OR_SUB_CON_GD",
    "XOR_UNIQUE_SUB_CON_GD",
    "NOT_SUB_CON_GD",
    "IMPLY_SUB_CON_GD",
    "IF_THEN_ELSE_SUB_CON_GD",
    "EXISTS_SUB_CON_GD",
    "EXISTS_UNIQUE_SUB_CON_GD",
    "FORALL_SUB_CON_GD",
    "GD",
    "GOAL_MODALITY",
    "ASSIGN_LOCAL_VAR",
    "FUNCTION_OR_VARIABLE",
    "LOCAL_VALUE",
    "AND_GD",
    "OR_GD",
    "XOR_UNIQUE_GD",
    "NOT_GD",
    "IMPLY_GD",
    "IF_THEN_ELSE_GD",
    "EXISTS_GD",
    "EXISTS_UNIQUE_GD",
    "FORALL_GD",
    "ATOMIC_FORMULA",
    "TERM",
    "FUNCTION_TERM_OR_CONSTANT",
    "LITERAL",
    "NOT_ATOMIC_FORMULA",
    "F_COMP",
    "BINARY_COMP",
    "GREATER_COMP",
    "GREATER_EQUAL_COMP",
    "LESS_EQUAL_COMP",
    "LESS_COMP",
    "EQUAL_COMP",
    "F_EXP",
    "NUMBER",
    "OP",
    "ADD_OP",
    "SUBSTRACT_OP",
    "MULTIPLY_OP",
    "DIVIDE_OP",
    "MOD_OP",
    "MAX_OP",
    "MIN_OP",
    "EXPT_OP",
    "SQRT_OP",
    "ABS_OP",
    "LOG_OP",
    "EXP_OP",
    "ROUND_OP",
    "INT_OP",
    "FLOOR_OP",
    "CEIL_OP",
    "F_HEAD",
    "FUNCTION_HEAD",
    "FUNCTION_HEAD_OR_FUNCTOR",
    "DECLARE_DEFINED_SYMBOLS",
    "STRUCTURE_DEF",
    "DEFINED_FORMULA_DECLARATION",
    "DEFINED_FORMULA",
    "ACTION_DEF",
    "ACTION_NAME",
    "ACTION_DEF_BODY",
    "PRE_GD",
    "EMPTY_OR",
    "AND_PRE_GD",
    "FORALL_PRE_GD",
    "PREF_GD",
    "NAMED_PREF_GD",
    "PREF_NAME",
    "EFFECT",
    "AND_C_EFFECT",
    "C_EFFECT",
    "FORALL_EFFECT",
    "WHEN_CON_EFFECT",
    "COND_EFFECT",
    "AND_P_EFFECT",
    "P_EFFECT",
    "F_EXP_OR_TERM",
    "F_EXP_OR_TERM_OR_UNDEFINED",
    "ASSIGN_OP",
    "ASSIGN",
    "SCALE_UP",
    "SCALE_DOWN",
    "INCREASE",
    "DECREASE",
    "DURATION_ACTION_DEF",
    "DA_DEF_BODY",
    "DURATION_CONSTRAINT",
    "AND_SIMPLE_DURATION_CONSTRAINT",
    "SIMPLE_DURATION_CONSTRAINT",
    "AT_SIMPLE_DURATION_CONSTRAINT",
    "AT_START_SIMPLE_DURATION_CONSTRAINT",
    "AT_END_SIMPLE_DURATION_CONSTRAINT",
    "D_OP",
    "EQUAL_D_OP",
    "GEQUAL_D_OP",
    "LEQUAL_D_OP",
    "VAR_DURATION",
    "D_VALUE",
    "DA_GD",
    "FORALL_DA_GD",
    "AND_DA_GD",
    "PREF_TIMED_GD",
    "NAMED_PREF_TIMED_GD",
    "TIMED_GD",
    "OVER_TIMED_GD",
    "OVER_ALL_TIMED_GD",
    "AT_TIMED_GD",
    "AT_START_TIMED_GD",
    "AT_END_TIMED_GD",
    "INTERVAL",
    "DA_EFFECT",
    "WHEN_DA_EFFECT",
    "FORALL_DA_EFFECT",
    "AND_DA_EFFECT",
    "TIMED_EFFECT",
    "AT_F_ASSIGN_DA_EFFECT",
    "AT_START_F_ASSIGN_DA_EFFECT",
    "AT_END_F_ASSIGN_DA_EFFECT",
    "AT_DA_EFFECT",
    "AT_START_DA_EFFECT",
    "AT_END_DA_EFFECT",
    "ASSIGN_OP_T",
    "INCREASE_ASSIGN_OP_T",
    "DECREASE_ASSIGN_OP_T",
    "F_EXP_T",
    "CONTINOUS_VARIABLE",
    "F_EXP_DA",
    "DA_OP",
    "DA_ADD_OP",
    "DA_SUBSTRACT_OP",
    "DA_MULTIPLY_OP",
    "DA_DIVIDE_OP",
    "DERIVED_DEF",
    "DERIVED_DEF_DECLARATION",
    "DEFINED_PREDICATE",
    "DEFINED_PREDICATE_DECLARATION",
    "DEFINED_FUNCTION",
    "DEFINED_FUNCTION_DECLARATION",
    "LOCAL_VARS",
    "PROBLEM",
    "PROBLEM_NAME",
    "DOMAIN_NAME",
    "OBJECT_DECLARATION",
    "INIT",
    "INIT_EL",
    "EQUAL_INIT_EL",
    "NUMBER_OR_CONSTANT",
    "TIMED_LITERAL",
    "GOAL",
    "CONSTRAINTS",
    "PREF_CON_GD",
    "AND_PREF_CON_GD",
    "NAMED_PREF_CON_GD",
    "FORALL_PREF_CON_GD",
    "METRIC_SPEC",
    "MAXIMIZE",
    "MINIMIZE",
    "METRIC_F_EXP",
    "VIOLATED_PREF_EXP",
    "CONSTANT_F_HEAD",
    "CONSTANT_FUNCTION_HEAD",
    "CONSTANT_FUNCTION_HEAD_OR_FUNCTOR",
    "TOTAL_TIME",
    "MULTI_OP_METRIC_F_EXP",
    "MULTIPLY_NARITY_OP_METRIC_F_EXP",
    "DIVIDE_NARITY_OP_METRIC_F_EXP",
    "ADD_NARITY_OP_METRIC_F_EXP",
    "SUBSTRACT_NARITY_OP_METRIC_F_EXP",
  };
}
}
/* JavaCC - OriginalChecksum=a03e5c31871961cee1e8ac8928964056 (do not edit this line) */
