//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string BoolOrAll_All {
            get {
                return ResourceManager.GetString("BoolOrAll_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string BoolOrAll_False {
            get {
                return ResourceManager.GetString("BoolOrAll_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string BoolOrAll_True {
            get {
                return ResourceManager.GetString("BoolOrAll_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string FactsContainerTypeOrAll_All {
            get {
                return ResourceManager.GetString("FactsContainerTypeOrAll_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitset of predicates.
        /// </summary>
        internal static string FactsContainerTypeOrAll_Bitset {
            get {
                return ResourceManager.GetString("FactsContainerTypeOrAll_Bitset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashset of literal IDs.
        /// </summary>
        internal static string FactsContainerTypeOrAll_Hashset {
            get {
                return ResourceManager.GetString("FactsContainerTypeOrAll_Hashset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeset of literal IDs.
        /// </summary>
        internal static string FactsContainerTypeOrAll_Treeset {
            get {
                return ResourceManager.GetString("FactsContainerTypeOrAll_Treeset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string FluentsContainerTypeOrAll_All {
            get {
                return ResourceManager.GetString("FluentsContainerTypeOrAll_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of fluents.
        /// </summary>
        internal static string FluentsContainerTypeOrAll_Array {
            get {
                return ResourceManager.GetString("FluentsContainerTypeOrAll_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashmap of fluent IDs.
        /// </summary>
        internal static string FluentsContainerTypeOrAll_Hashmap {
            get {
                return ResourceManager.GetString("FluentsContainerTypeOrAll_Hashmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treemap of fluent IDs.
        /// </summary>
        internal static string FluentsContainerTypeOrAll_Treemap {
            get {
                return ResourceManager.GetString("FluentsContainerTypeOrAll_Treemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_All {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best first search.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_BestFirst {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_BestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadth first search.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_BreadthFirst {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_BreadthFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadth first priority search.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_BreadthFirstPriority {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_BreadthFirstPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth best first search.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_DepthBestFirst {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_DepthBestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth first search.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_DepthFirst {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_DepthFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth first search without backtracking.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_DepthFirstNoBacktracking {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_DepthFirstNoBacktracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth first priority search.
        /// </summary>
        internal static string GraphSearchStrategyOrAll_DepthFirstPriority {
            get {
                return ResourceManager.GetString("GraphSearchStrategyOrAll_DepthFirstPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string PreprocessingLevelOrAll_All {
            get {
                return ResourceManager.GetString("PreprocessingLevelOrAll_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preprocessing.
        /// </summary>
        internal static string PreprocessingLevelOrAll_NoPreprocessing {
            get {
                return ResourceManager.GetString("PreprocessingLevelOrAll_NoPreprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocess preconditions only.
        /// </summary>
        internal static string PreprocessingLevelOrAll_PreprocessPreconditions {
            get {
                return ResourceManager.GetString("PreprocessingLevelOrAll_PreprocessPreconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocess preconditions and defined formulas.
        /// </summary>
        internal static string PreprocessingLevelOrAll_PreprocessPreconditionsAndDefinedFormulas {
            get {
                return ResourceManager.GetString("PreprocessingLevelOrAll_PreprocessPreconditionsAndDefinedFormulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SetImplementationTypeOrAll_All {
            get {
                return ResourceManager.GetString("SetImplementationTypeOrAll_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashset (uses hash codes).
        /// </summary>
        internal static string SetImplementationTypeOrAll_Hashset {
            get {
                return ResourceManager.GetString("SetImplementationTypeOrAll_Hashset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeset (uses IComparable).
        /// </summary>
        internal static string SetImplementationTypeOrAll_Treeset {
            get {
                return ResourceManager.GetString("SetImplementationTypeOrAll_Treeset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string WorldTypeOrAll_All {
            get {
                return ResourceManager.GetString("WorldTypeOrAll_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom world implementation.
        /// </summary>
        internal static string WorldTypeOrAll_Custom {
            get {
                return ResourceManager.GetString("WorldTypeOrAll_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashset of IDs.
        /// </summary>
        internal static string WorldTypeOrAll_Qualified {
            get {
                return ResourceManager.GetString("WorldTypeOrAll_Qualified", resourceCulture);
            }
        }
    }
}
